name: Release
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.31.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            dist/index.js
            dist/deobfuscate.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}